name: 'Greetings!'
description: 'Send a greeting message when the Action is run'
inputs:
  name:  # id of input
    description: 'name of repo owner'
    required: true
    default: 'World'

runs:
  using: 'node12'
  main: 'dist/index.js'
